services:
  postgres:
    image: postgres:15
    container_name: food_delivery_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: complex_password
      POSTGRES_DB: food_delivery
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
